# Generated by Django 4.2 on 2026-05-08 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BackupLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periodo', models.CharField(db_index=True, max_length=10)),
                ('anio', models.CharField(max_length=4)),
                ('programa', models.CharField(max_length=30)),
                ('curso_id', models.IntegerField()),
                ('shortname', models.CharField(max_length=120)),
                ('fullname', models.CharField(max_length=255)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('EN_PROCESO', 'En proceso'), ('COMPLETADO', 'Completado'), ('FALLIDO', 'Fallido')], db_index=True, default='PENDIENTE', max_length=20)),
                ('celery_task_id', models.CharField(blank=True, max_length=255, null=True)),
                ('error_detalle', models.TextField(blank=True, null=True)),
                ('fecha_inicio', models.DateTimeField(auto_now_add=True)),
                ('fecha_fin', models.DateTimeField(blank=True, null=True)),
                ('nombre_archivo', models.CharField(blank=True, max_length=255, null=True)),
                ('ruta_local', models.CharField(blank=True, max_length=512, null=True)),
                ('tamano_mb', models.FloatField(blank=True, null=True)),
                ('checksum_sha256', models.CharField(blank=True, max_length=64, null=True)),
            ],
            options={
                'verbose_name': 'Backup',
                'verbose_name_plural': 'Backups',
                'ordering': ['-fecha_inicio'],
            },
        ),
        migrations.AddIndex(
            model_name='backuplog',
            index=models.Index(fields=['periodo', 'estado'], name='backups_bac_periodo_fc787a_idx'),
        ),
        migrations.AddIndex(
            model_name='backuplog',
            index=models.Index(fields=['curso_id'], name='backups_bac_curso_i_b9b99a_idx'),
        ),
    ]
