# Generated by Django 4.2 on 2026-05-11 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backups', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='backuplog',
            name='backups_bac_curso_i_b9b99a_idx',
        ),
        migrations.AddField(
            model_name='backuplog',
            name='categoria_carpeta',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='backuplog',
            name='categoria_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='backuplog',
            name='categoria_nombre',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='backuplog',
            name='tipo',
            field=models.CharField(choices=[('PERIODO', 'Por periodo'), ('CATEGORIA', 'Por categoría')], db_index=True, default='PERIODO', max_length=20),
        ),
        migrations.AddField(
            model_name='backuplog',
            name='tipo_ruta',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddIndex(
            model_name='backuplog',
            index=models.Index(fields=['categoria_id', 'estado'], name='backups_bac_categor_1c05a7_idx'),
        ),
        migrations.AddIndex(
            model_name='backuplog',
            index=models.Index(fields=['tipo', 'estado'], name='backups_bac_tipo_45c95b_idx'),
        ),
    ]
