# Generated by Django 4.2 on 2026-05-11 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backups', '0002_remove_backuplog_backups_bac_curso_i_b9b99a_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='backuplog',
            name='anio',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
    ]
